### ISSUE TITLE
打开javacript.jsx格式文件会报错

### ISSUE THREAD

**Issue by leisurelicht** [ncm2/ncm2-tern#2]
报错信息：
> [ncm2_tern@yarp] Traceback (most recent call last):
[ncm2_tern@yarp]   File "/Users/Licht/.vim/plugged/nvim-yarp/pythonx/yarp.py", line 59, in <module>
[ncm2_tern@yarp]     module_obj = importlib.import_module(module)
[ncm2_tern@yarp]   File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
[ncm2_tern@yarp]     return _bootstrap._gcd_import(name[level:], package, level)
[ncm2_tern@yarp]   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
[ncm2_tern@yarp]   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
[ncm2_tern@yarp]   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
[ncm2_tern@yarp]   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
[ncm2_tern@yarp]   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
[ncm2_tern@yarp]   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
[ncm2_tern@yarp]   File "/Users/Licht/.vim/plugged/ncm2-tern/pythonx/ncm2_tern.py", line 171, in <module>
[ncm2_tern@yarp]     source = Source(vim)
[ncm2_tern@yarp]   File "/Users/Licht/.vim/plugged/ncm2-tern/pythonx/ncm2_tern.py", line 94, in __init__
[ncm2_tern@yarp]     'split(globpath(&rtp,"node_modules/tern/bin/tern",1),"\\n")[0]')
[ncm2_tern@yarp]   File "/usr/local/lib/python3.7/site-packages/neovim/api/nvim.py", line 280, in eval
[ncm2_tern@yarp]     return self.request('nvim_eval', string, **kwargs)
[ncm2_tern@yarp]   File "/usr/local/lib/python3.7/site-packages/neovim/api/nvim.py", line 170, in request
[ncm2_tern@yarp]     res = self._session.request(name, *args, **kwargs)
[ncm2_tern@yarp]   File "/usr/local/lib/python3.7/site-packages/neovim/msgpack_rpc/session.py", line 100, in request
[ncm2_tern@yarp]     raise self.error_wrapper(err)
[ncm2_tern@yarp] neovim.api.nvim.NvimError: b'Vim:E684: list index out of range: 0'
[ncm2_tern@yarp] Job is dead. cmd=['/usr/local/bin/python3', '-u', '/Users/Licht/.vim/plugged/nvim-yarp/pythonx/yarp.py', '/var/folders/v7/1dtcydw51_s1ydkmypx1fggh0000gn/T/nvimqHymaZ/0', 7, 'ncm2_tern']

**Comment by roxma** [comment]
Make sure you have done `npm install` for this plugin.
