### ISSUE TITLE
extra single quote problem

### ISSUE THREAD

**Issue by hackingcat** [ncm2/ncm2-tern#5]
https://github.com/carlitux/deoplete-ternjs/issues/25

**Comment by hackingcat** [comment]
https://asciinema.org/a/CoGGJrKTbhTO3NmTCPSyTdbC9

**Comment by hackingcat** [comment]
https://asciinema.org/a/DJCt0HaKhpd4YHCrZrKXXK8Dg

**Comment by roxma** [comment]
I can reproduce the issue with `<c-x><c-o>` and `tern_for_vim`

This is actually ternjs issue.

**Comment by hackingcat** [comment]
Indeed,this should be a bug of ternjs.But deoplete-ternjs fixed the problem,you can have a try.

**Comment by pittcat** [comment]
I switched from deoplete to ncm2 .Deoplete-ternjs seems better on dealing with the problem，even if the problem is harmless.Maybe we can reopen the issue.@roxma
